### ISSUE TITLE
RdfFetch does not provide access to WebId

### ISSUE THREAD

**Issue by angel-araya-jd** [janeirodigital/sai-js#13]
RdfFetch object does not provide access to the user WebId. Since Fetch implementation shouldn't deviate from the standard API then the WebId has to be provided through other means. In the case of `@inrupt/solid-client-authn-browser` and family this is done via the `Session` object which has a `webId` and a `loggedIn` property.

I think the solution is to have the application developer provide the WebId and the fetch function.

**Comment by elf-pavlik** [comment]
Yes, we were planning to update that tomorrow.

**Comment by elf-pavlik** [comment]
@angel-araya-jd we have it ready in https://github.com/elf-pavlik/sai-js/blob/monday/packages/application/src/application.ts#L60
