### ISSUE TITLE
NPM package (rc.5) does not reflect the changes intended in #32

### ISSUE THREAD

**Issue by angelaraya** [janeirodigital/sai-js#33]
The packages uploaded in NPM do not coincide with the changes we meant to include in #32. While the source code matches, the generated code differs in some key aspects:

```diff
~ diff /from-npm/.../data-model/dist/cjs/readable/data-grant.js /local/.../data-model/dist/cjs/readable/data-grant.js
17c17,18
< class AbstractDataGrant extends __1.ReadableResource {
---
> const _1 = require(".");
> class AbstractDataGrant extends _1.ReadableResource {
49c50
<     typescript_memoize_1.Memoize(),
---
```

The missing `const _1 = require(".");` means that we see the same `Class is undefined` error when using the package in the service implementation. My guess is that the builder used to build and publish is using a different version/environment.

My local environment is running:
- `node 16.13.1`
- `npm 8.5.3`
- `tsc 4.5.4`

**Comment by elf-pavlik** [comment]
I updated TS to the latest and published rc.6

Also created #34 to avoid such issues in the future.

Please reopen if there are still issues with rc.6

**Comment by angelaraya** [comment]
`rc.6` is working as expected 👍🏻
