### ISSUE TITLE
improve build script during development

### ISSUE THREAD

**Issue by elf-pavlik** [janeirodigital/sai-js#50]
Currently, we do `clean` and `build:ts`, as part of `build`. The `clean` part is problematic during development since messes up filesystem watchers like `ng start` and `TS server`. Most likely we only need to `clean` before publishing and can just re-run build in development.

**Comment by angelaraya** [comment]
I have not run into this issue with my file system, but I don't see the harm in removing it either. I image this will be closed once #51 is merged

**Comment by elf-pavlik** [comment]
Yes, we already did it in a few packages and just need to make sure we change it in all of them.
