### ISSUE TITLE
error Couldn't find package "@digita-ai/handlersjs-core@^0.19.3" 

### ISSUE THREAD

**Issue by thhck** [janeirodigital/sai-js#68]
Hello,

Using node 16.19.1 and npm v6.14.18 I was not able to install following the README instruction. 

`yarn install` returned the following error:

```
error Couldn't find package "@digita-ai/handlersjs-core@^0.19.3" required by "@janeirodigital/sai-server@1.0.0-rc.20" on the "npm" registry.
```

Do I need to follow this step too ? https://github.com/digita-ai/handlersjs#usage

**Comment by elf-pavlik** [comment]
Hi,

> Do I need to follow this step too ? https://github.com/digita-ai/handlersjs#usage

Yes! I've just added some guidance to the README as well:

https://github.com/janeirodigital/sai-js#github-packages

Thank you for bringing up to our attention that it was missing!
