### ISSUE TITLE
Following instructions in readme does not work

### ISSUE THREAD

**Issue by Darkros1245** [janeirodigital/sai-js#71]
The documentation in the readme seems to be outdated?
I have tried following the guide in readme.md, but it does not seem to work.
I got as far as being able to log in with the "alice" account, but then when I was redirected nothing happened, and in the console I could see that an error had occurred.
I have tried to execute whats in "ui/authorization/" with yarn dev, but it fails on line 56 in "ui/authorization/src/backend.ts".
I have also tried to execute whats in "examples/vuejectron/" also with yarn dev, but it fails on line 19 in "packages/utils/src/discovery.ts".
For both cases I had the solid community server running from "packages/css-storage-fixture/".

It would be nice with a comprehensive guide to run the example.

**Comment by elf-pavlik** [comment]
Hi, thank you for reporting!
Indeed we made some major changes in recent days, I'm going update the README sometime today/tomorrow. You will get notification once this issue gets closed.

**Comment by elf-pavlik** [comment]
@Darkros1245 could you please try https://github.com/janeirodigital/sai-js#development

There are 2 small gotchas:
1.  On `localhost:4200` after *Connect server* redirect you will see empty screen. This is fine and we are about to push default dashboard later this week. Authorization views already work when app redirects to the authorization agent.
2. On `localhost:4500` we have a bug with vite dev server. We are still looking for solution but it only happens on first navigation, navigating to `localhost:4500` second time should work just fine.

Please feel free to close this issue if the updated readme works for you.

**Comment by Darkros1245** [comment]
Thanks @elf-pavlik, it seems to work now, looking forward to seeing/trying the dashboard.
