### ISSUE TITLE
[readme instructions] `alice@example.org` account not created

### ISSUE THREAD

**Issue by michielbdejong** [janeirodigital/sai-js#73]
I was able to follow the readme instructions up to https://github.com/janeirodigital/sai-js?tab=readme-ov-file#bootstrapping

But when I browse to http://localhost:3000 I don't see a signup button but no login button
Browsing to http://localhost:3000/.account/login/password/ I cannot log in with the combination of
Username: `alice@example.org`
Password: `password`

After I sign up with username `alice@example.org` and password `password` and try to create a pod called `alice` it says that pod already exists. The logs show:
```
css-storage-fixture:dev: 2024-02-05T10:20:40.416Z [BasePasswordStore] {Primary} warn: Trying to get account info for unknown email alice@example.org
css-storage-fixture:dev: 2024-02-05T10:21:32.235Z [BasePodStore] {Primary} warn: Pod creation failed for account 5a4a1f31-adfe-46c6-9eb3-c0c78d83ebf3: There already is a resource at http://localhost:3000/alice/
```

**Comment by elf-pavlik** [comment]
Sorry, the email should be `alice@acme.example`
