### ISSUE TITLE
[readme instructions] demo app not working

### ISSUE THREAD

**Issue by michielbdejong** [janeirodigital/sai-js#75]
When browsing to http://localhost:4500 I see this:

<img width="1262" alt="Screenshot 2024-02-05 at 12 43 21" src="https://github.com/janeirodigital/sai-js/assets/408412/1153787a-43c6-4609-a5ea-99fe21a6b126">

**Comment by michielbdejong** [comment]
Clicking the 'Request authorization' button triggers the errors in the browser console as shown.

**Comment by elf-pavlik** [comment]
I'm going to take a look at it tomorrow. I am trying to remember if we fail gracefully if the authorization agent doesn't exist yet. You could attempt to open http://localhost:4200 first and authenticate there; this will create an authorization agent for the WebID you authenticate with.

**Comment by michielbdejong** [comment]
I'm getting one step further now, using `alice@acme.example` / `password` but now I run into:
<img width="523" alt="Screenshot 2024-02-10 at 17 14 02" src="https://github.com/janeirodigital/sai-js/assets/408412/bf223198-d90c-410b-b95e-6cc19a43707c">


Can we maybe do a screensharing session to debug this?

**Comment by michielbdejong** [comment]
Ah wait I think I got one step further:
<img width="702" alt="Screenshot 2024-02-10 at 17 20 02" src="https://github.com/janeirodigital/sai-js/assets/408412/665f237b-8b77-4cd2-a938-e6ebc0e4e672">
 
But I still can't launch the app.

**Comment by elf-pavlik** [comment]
Once you authenticate on port 4200 you can go to port 4500 and request authorization from the app.
You could also use the add application and paste the client ID of the vujectron, but the other way should be easier.

**Comment by michielbdejong** [comment]
Ah, that's confusing!
So this time I browsed away from localhost:4200 to localhost:4500, and now I see this:
<img width="1101" alt="Screenshot 2024-02-14 at 16 47 24" src="https://github.com/janeirodigital/sai-js/assets/408412/df9cd1d1-9418-4665-b6cd-ea96239b7a8a">

**Comment by elf-pavlik** [comment]
This is some weird vite dev server bug. It can happen on the first load and goes away after a simple page reload. I also noticed that disabling caching in dev tools prevents it from happening.

**Comment by michielbdejong** [comment]
Thanks for the screensharing, it works now!
```







































pnpm dev
pnpm watch
http://localhost:4200
http://localhost:4500
http://localhost:4500/redirect
http://localhost:4500
http://localhost:4200/applications
```

```
bob@yoyodyne.example 
https://github.com/janeirodigital/sai-js/tree/main/packages/css-storage-fixture#accounts
```
