### ISSUE TITLE
How does the app-first login flow look with SAI?

### ISSUE THREAD

**Issue by michielbdejong** [janeirodigital/sai-js#76]
With SAI, Solid apps will no longer have a 'Log in with your WebID' button, right? Instead if the user is at an app using it in not-logged-in mode and wants to connect their Solid pod, then they would click 'connect your pod' and this would redirect the user to their authorization agent, along with an access request, probably?

Is there a screencast of how this part of the flow works?

IIUC most screencasts I've seen either start at the authorization agent, or if the app is shown then the user is already authenticated.

**Comment by elf-pavlik** [comment]
Currently, the user has to be authenticated with their authorization agent first; this way, the authorization agent can access the storage of its user. Then, the user has to first authenticate with the app, using solid oidc, and after that, authorize the app by another redirect to the authorization agent.

The UX could be improved by integrating Solid OIDC OP and SAI Authorization Agent; this way, users can authenticate and authorize in a single redirect.

**Comment by michielbdejong** [comment]
Thanks!
